### PR TITLE
Fail faster for common server errors (e.g. 404).

### LINKED ISSUE #14: Detect and fail-fast for things like a fileserver 404 in tests.
If you try to point `x-test-cli` to like `https://localhost:8080/does/not/exist.html`… it will just hang, unhelpfully. There are two things we should do:

1. Detect obvious cases and fail-fast — “are you sure that the url is right?”
2. Add a global timeout race a the test root as a failsafe — if we don’t get a result in 30s… just bail.

### PR DESCRIPTION
**Pull request by theengineear**
This change set covers some common cases:

- Server takes to long to respond for whatever reason - timeout / bail.
- Server responds with 4xx / 5xx error — bail.
- Server response with non HTML — bail.

Closes #14.

### CODE REVIEW

File: x-test-cli-browser.js [hunk 1]
```diff
@@ -23,30 +23,39 @@ export class XTestCliBrowserPuppeteer {
...
 
-    await page.goto(url);
+      // Signal intent to content-negotiating servers so they can 4xx early
+      //  instead of serving a non-HTML variant. Static servers ignore this.
+      await page.setExtraHTTPHeaders({ Accept: 'text/html' });
 
-    const { coverageRequested } = await page.evaluate(XTestCliBrowserPuppeteer.#runScript());
+      const response = await page.goto(url);
+      if (response && response.status() >= 400) {
+        throw new Error(`Got HTTP ${response.status()} for ${url}. Is the url correct?`);
```
Comment (theengineear) [inline x-test-cli-browser.js:46]: Fail fast for `4xx` / `5xx` errors. There is no way it would pass, why wait?

File: x-test-cli.js [hunk 2]
```diff
@@ -99,17 +110,30 @@ const driverOptions = {
...
 // Run the browser driver. On any catastrophic failure (browser launch,
 //  navigation, etc.) emit `Bail out!` through the reporter so it gets colorized
 //  and the scanner records the bailed state, then dump the error to stderr
 //  (outside the TAP stream) and exit 1.
+const timeoutMessage = `Timed out after ${runTimeout}ms waiting for x-test root at ${url}. Use --timeout=<ms> to extend.`;
 try {
   switch (options.client) {
     case 'puppeteer':
-      await XTestCliBrowserPuppeteer.run(driverOptions);
+      await withTimeout(XTestCliBrowserPuppeteer.run(driverOptions), runTimeout, timeoutMessage);
```
Comment (theengineear) [inline x-test-cli.js:133]: Add a global timeout race to the entire page load. It should be quite hard for this to truly, indefinitely hang now.
